name: Monitor Scraper Tiendas Máx
on:
  schedule:
    - cron: '0 8 * * *'  # Ejecuta a las 8:00 AM UTC (2:00 AM hora Guatemala)
  workflow_dispatch:     # Permite ejecución manual desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest  # Máquina virtual Linux gratuita

    steps:
      # 1. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 2. Copia el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener este archivo

      # 4. Ejecuta el scraper
      - name: Run scraper
        run: python max_spider.py  # Tu script principal

      # 5. Opcional: Notificar errores en Slack
      - name: Notify Slack on failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: '⚠️ Fallo en scraper: ${{ github.repository }}. Revisar cambios en selectores.'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}  # Configurar en Secrets de GitHub
